// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// seq_n
CharacterVector seq_n(CharacterVector labels, int n_buckets, int n_reps, bool edge_streaks, bool repeats);
RcppExport SEXP _rmseq_seq_n(SEXP labelsSEXP, SEXP n_bucketsSEXP, SEXP n_repsSEXP, SEXP edge_streaksSEXP, SEXP repeatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_buckets(n_bucketsSEXP);
    Rcpp::traits::input_parameter< int >::type n_reps(n_repsSEXP);
    Rcpp::traits::input_parameter< bool >::type edge_streaks(edge_streaksSEXP);
    Rcpp::traits::input_parameter< bool >::type repeats(repeatsSEXP);
    rcpp_result_gen = Rcpp::wrap(seq_n(labels, n_buckets, n_reps, edge_streaks, repeats));
    return rcpp_result_gen;
END_RCPP
}
// com_n
List com_n(CharacterVector labels, int n_buckets, int n_reps, bool edge_streaks, bool repeats);
RcppExport SEXP _rmseq_com_n(SEXP labelsSEXP, SEXP n_bucketsSEXP, SEXP n_repsSEXP, SEXP edge_streaksSEXP, SEXP repeatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_buckets(n_bucketsSEXP);
    Rcpp::traits::input_parameter< int >::type n_reps(n_repsSEXP);
    Rcpp::traits::input_parameter< bool >::type edge_streaks(edge_streaksSEXP);
    Rcpp::traits::input_parameter< bool >::type repeats(repeatsSEXP);
    rcpp_result_gen = Rcpp::wrap(com_n(labels, n_buckets, n_reps, edge_streaks, repeats));
    return rcpp_result_gen;
END_RCPP
}
// seq_n_ix_R
IntegerVector seq_n_ix_R(CharacterVector labels, int n_buckets, int n_reps, bool edge_streaks, bool repeats);
RcppExport SEXP _rmseq_seq_n_ix_R(SEXP labelsSEXP, SEXP n_bucketsSEXP, SEXP n_repsSEXP, SEXP edge_streaksSEXP, SEXP repeatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_buckets(n_bucketsSEXP);
    Rcpp::traits::input_parameter< int >::type n_reps(n_repsSEXP);
    Rcpp::traits::input_parameter< bool >::type edge_streaks(edge_streaksSEXP);
    Rcpp::traits::input_parameter< bool >::type repeats(repeatsSEXP);
    rcpp_result_gen = Rcpp::wrap(seq_n_ix_R(labels, n_buckets, n_reps, edge_streaks, repeats));
    return rcpp_result_gen;
END_RCPP
}
// com_n_ix_R
List com_n_ix_R(CharacterVector labels, int n_buckets, int n_reps, bool edge_streaks, bool repeats);
RcppExport SEXP _rmseq_com_n_ix_R(SEXP labelsSEXP, SEXP n_bucketsSEXP, SEXP n_repsSEXP, SEXP edge_streaksSEXP, SEXP repeatsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type labels(labelsSEXP);
    Rcpp::traits::input_parameter< int >::type n_buckets(n_bucketsSEXP);
    Rcpp::traits::input_parameter< int >::type n_reps(n_repsSEXP);
    Rcpp::traits::input_parameter< bool >::type edge_streaks(edge_streaksSEXP);
    Rcpp::traits::input_parameter< bool >::type repeats(repeatsSEXP);
    rcpp_result_gen = Rcpp::wrap(com_n_ix_R(labels, n_buckets, n_reps, edge_streaks, repeats));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rmseq_seq_n", (DL_FUNC) &_rmseq_seq_n, 5},
    {"_rmseq_com_n", (DL_FUNC) &_rmseq_com_n, 5},
    {"_rmseq_seq_n_ix_R", (DL_FUNC) &_rmseq_seq_n_ix_R, 5},
    {"_rmseq_com_n_ix_R", (DL_FUNC) &_rmseq_com_n_ix_R, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_rmseq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
