# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.seq_n <- function(labels, n_buckets, n_reps, edge_streaks, repeats) {
    .Call(`_rmseq_seq_n`, labels, n_buckets, n_reps, edge_streaks, repeats)
}

.com_n <- function(labels, n_buckets, n_reps, edge_streaks, repeats) {
    .Call(`_rmseq_com_n`, labels, n_buckets, n_reps, edge_streaks, repeats)
}

.seq_n_ix <- function(labels, n_buckets, n_reps, edge_streaks = FALSE, repeats = FALSE) {
    .Call(`_rmseq_seq_n_ix_R`, labels, n_buckets, n_reps, edge_streaks, repeats)
}

.com_n_ix <- function(labels, n_buckets, n_reps, edge_streaks = FALSE, repeats = FALSE) {
    .Call(`_rmseq_com_n_ix_R`, labels, n_buckets, n_reps, edge_streaks, repeats)
}

